apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31234
  selector:
    app: demo
  
